export const dummySentences = [
  {
    id: 1,
    topic_id: 1, // ㄱㄴㄷ (자음별 발음 연습)
    korean: '가방을 들고 나갔어요.',
    translation: 'I went out carrying a bag.',
    modelPronunciation: 'https://dummy-audio.com/model1.mp3',
  },
  {
    id: 2,
    topic_id: 1,
    korean: '나무 아래에서 쉬고 있어요.',
    translation: 'I am resting under the tree.',
    modelPronunciation: 'https://dummy-audio.com/model2.mp3',
  },
  {
    id: 3,
    topic_id: 1,
    korean: '다리가 아파서 쉬어야겠어요.',
    translation: 'My legs hurt, so I should take a break.',
    modelPronunciation: 'https://dummy-audio.com/model3.mp3',
  },
  {
    id: 4,
    topic_id: 1,
    korean: '고양이가 창밖을 바라보고 있어요.',
    translation: 'The cat is looking out the window.',
    modelPronunciation: 'https://dummy-audio.com/model4.mp3',
  },
  {
    id: 5,
    topic_id: 1,
    korean: '노래를 듣는 걸 좋아해요.',
    translation: 'I like listening to music.',
    modelPronunciation: 'https://dummy-audio.com/model5.mp3',
  },
  {
    id: 6,
    topic_id: 1,
    korean: '달이 밝게 빛나고 있어요.',
    translation: 'The moon is shining brightly.',
    modelPronunciation: 'https://dummy-audio.com/model6.mp3',
  },
  {
    id: 7,
    topic_id: 2, // 일상 회화
    korean: '안녕하세요.',
    translation: 'Hello.',
    modelPronunciation: 'https://dummy-audio.com/model7.mp3',
  },
  {
    id: 8,
    topic_id: 2,
    korean: '저는 [이름]입니다.',
    translation: 'I am [name].',
    modelPronunciation: 'https://dummy-audio.com/model8.mp3',
  },
  {
    id: 9,
    topic_id: 2,
    korean: '지금 몇 시인가요?',
    translation: 'What time is it now?',
    modelPronunciation: 'https://dummy-audio.com/model9.mp3',
  },
  {
    id: 10,
    topic_id: 2,
    korean: '오늘 날씨가 참 좋네요!',
    translation: 'The weather is really nice today!',
    modelPronunciation: 'https://dummy-audio.com/model10.mp3',
  },
  {
    id: 11,
    topic_id: 2,
    korean: '커피 한 잔 주세요.',
    translation: 'One cup of coffee, please.',
    modelPronunciation: 'https://dummy-audio.com/model11.mp3',
  },
  {
    id: 12,
    topic_id: 2,
    korean: '이 옷은 얼마인가요?',
    translation: 'How much is this clothing?',
    modelPronunciation: 'https://dummy-audio.com/model12.mp3',
  },
  {
    id: 13,
    topic_id: 3, // 학교
    korean: '학교에 가는 길이에요.',
    translation: 'I am on my way to school.',
    modelPronunciation: 'https://dummy-audio.com/model13.mp3',
  },
  {
    id: 14,
    topic_id: 3,
    korean: '오늘 수업이 몇 시에 시작하나요?',
    translation: 'What time does class start today?',
    modelPronunciation: 'https://dummy-audio.com/model14.mp3',
  },
  {
    id: 15,
    topic_id: 3,
    korean: '숙제를 다 끝냈어요.',
    translation: 'I finished my homework.',
    modelPronunciation: 'https://dummy-audio.com/model15.mp3',
  },
  {
    id: 16,
    topic_id: 3,
    korean: '친구들과 도서관에서 공부했어요.',
    translation: 'I studied with my friends in the library.',
    modelPronunciation: 'https://dummy-audio.com/model16.mp3',
  },
  {
    id: 17,
    topic_id: 3,
    korean: '선생님께 질문이 있어요.',
    translation: 'I have a question for the teacher.',
    modelPronunciation: 'https://dummy-audio.com/model17.mp3',
  },
  {
    id: 18,
    topic_id: 3,
    korean: '체육 시간에 농구를 했어요.',
    translation: 'We played basketball during PE class.',
    modelPronunciation: 'https://dummy-audio.com/model18.mp3',
  },
  {
    id: 19,
    topic_id: 4, // 회사
    korean: '출근 시간이 몇 시인가요?',
    translation: 'What time is the work start time?',
    modelPronunciation: 'https://dummy-audio.com/model19.mp3',
  },
  {
    id: 20,
    topic_id: 4,
    korean: '회의가 곧 시작돼요.',
    translation: 'The meeting will start soon.',
    modelPronunciation: 'https://dummy-audio.com/model20.mp3',
  },
  {
    id: 21,
    topic_id: 4,
    korean: '이 서류를 어디에 제출하면 되나요?',
    translation: 'Where should I submit this document?',
    modelPronunciation: 'https://dummy-audio.com/model21.mp3',
  },
  {
    id: 22,
    topic_id: 4,
    korean: '업무가 끝나면 연락 주세요.',
    translation: 'Please contact me when you finish work.',
    modelPronunciation: 'https://dummy-audio.com/model22.mp3',
  },
  {
    id: 23,
    topic_id: 4,
    korean: '이번 프로젝트의 마감일은 언제인가요?',
    translation: 'When is the deadline for this project?',
    modelPronunciation: 'https://dummy-audio.com/model23.mp3',
  },
  {
    id: 24,
    topic_id: 4,
    korean: '점심 식사 후 다시 회의실에서 만나요.',
    translation: 'Let’s meet again in the conference room after lunch.',
    modelPronunciation: 'https://dummy-audio.com/model24.mp3',
  },
];
