export const dummyPronunciationIssue = {
  id: 1,
  title: 'Difficulty pronouncing tense sounds (ㄲ)',
  accuracy: 35,
  totalErrorLogCount: 12,
  recommendSentences: [
    {
      id: 11,
      korean: '아빠가 빨간 꽃병을 꺼냈어요.',
      translation: 'Dad took out the red flower vase.',
      audioUrl: '',
      ipa: '',
      isPassed: null,
    },
    {
      id: 12,
      korean: '쭈꾸미 볶음이 정말 맛있어요.',
      translation: 'The stir-fried baby octopus is really tasty.',
      audioUrl: '',
      ipa: '',
      isPassed: null,
    },
    {
      id: 13,
      korean: '리모컨을 눌러서 TV를 켰어요.',
      translation: 'I pressed the remote control to turn on the TV.',
      audioUrl: '',
      ipa: '',
      isPassed: null,
    },
    {
      id: 14,
      korean: '달리기가 끝난 후 물을 마셨어요.',
      translation: 'I drank water after finishing the run.',
      audioUrl: '',
      ipa: '',
      isPassed: null,
    },
  ],
};
