export const dummyErrorLogList = {
  totalErrorLogCount: 9,
  errorLogs: [
    {
      id: 101,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '바', index: 1 }],
    },
    {
      id: 102,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 103,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 104,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 105,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 106,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 107,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 108,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
    {
      id: 109,
      translation: 'Dad took out the red flower vase.',
      correctText: '아빠가 빨간 꽃병을 꺼냈어요.',
      correctIpa: '[ap͈aga p͈algɐn k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      userText: '아바가 발간 꽃병을 꺼냈어요.',
      userIpa: '[abaga pargan k͈o̞p̚pjʌŋɯl kkʌnɛsʌjo]',
      errors: [{ char: '발', index: 4 }],
    },
  ],
};
